name: 'PR'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  semantic-title:
    name: 'Semantic title'
    uses: technology-studio/github-workflows/.github/workflows/_semantic-title.yml@98774916572d196a1ac57f0ec578395c6b3573e5 # main
    secrets: inherit
