name: Release
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  release:
    name: 'Release'
    uses: technology-studio/github-workflows/.github/workflows/_release.yml@98774916572d196a1ac57f0ec578395c6b3573e5 # main
    secrets: inherit
